apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backendlabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendlabel }}
    spec:
      containers:
        - name: {{ .Values.backendimage.name }}
          image: "{{ .Values.backendimage.repository }}"
          imagePullPolicy: {{ .Values.backendimage.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP