apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontendname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontendlabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontendlabel }}
    spec:
      containers:
        - name: {{ .Values.frontendimage.name }}
          image: "{{ .Values.frontendimage.repository }}"
          imagePullPolicy: {{ .Values.frontendimage.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP