apiVersion: v1
kind: Service
metadata:
  name: {{ include "multi-container-chart.fullname" . }}-2
  labels:
    {{- include "multi-container-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.servicebackend.type }}
  ports:
    - port: {{ .Values.servicebackend.port }}
      targetPort: http
      protocol: TCP
      name: http  
  selector:
    {{- include "multi-container-chart.selectorLabels" . | nindent 4 }}
